alias gsm='gnome-system-monitor'
alias calc='gnome-calculator'
alias spotify='flatpak run com.spotify.Client&'
alias codeblocks='flatpak run org.codeblocks.codeblocks'
alias lofi='/home/razi/bin/lofi'
alias stoplofi='/home/razi/bin/stoplofi'
alias vim='nvim'
